<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
// 2024

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'Korean',
	'DIRECTION'		=> 'ltr',
	'DATE_FORMAT'		=> '|Y-M-d|',	// 2024-03-16 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|Y-M-d H:i|',	// 2024-03-16 13:37 (with Relative days enabled)
	'USER_LANG'		=> 'ko',

// You can define different rules for the determination of plural forms here.
// See https://area51.phpbb.com/docs/dev/3.3.x/language/plurals.html for more information
// or ask the translation manager for help.
	'PLURAL_RULE'		=> 0,

	'1_DAY'			=> '하루',
	'1_MONTH'		=> '1 달',
	'1_YEAR'		=> '1 년',
	'2_WEEKS'		=> '2 주',
	'3_MONTHS'		=> '3 달',
	'6_MONTHS'		=> '6 달',
	'7_DAYS'		=> '7 일',

	'ACCOUNT_ALREADY_ACTIVATED'	=> '당신의 계정은 이미 활성화되었습니다.',
	'ACCOUNT_DEACTIVATED'		=> '당신의 계정은 수동으로 비활성화되었으며 관리자만 재활성화할 수 있습니다.',
	'ACP'				=> '관리 제어판',
	'ACP_SHORT'			=> 'ACP',
	'ACTIVE'			=> '활동적인',
	'ACTIVE_ERROR'			=> '지정된 사용자 이름은 현재 비활성 상태입니다. 계정 활성화에 문제가 있으면 게시판 관리자에게 문의하세요.',
	'ADMINISTRATOR'			=> '관리자',
	'ADMINISTRATORS'		=> '관리자',
	'AGE'				=> '나이',
	'AIM'				=> 'AIM',
	'AJAX_ERROR_TITLE'		=> 'AJAX 오류',
	'AJAX_ERROR_TEXT'		=> '요청을 처리하는 중에 문제가 발생했습니다.',
	'AJAX_ERROR_TEXT_ABORT'		=> '사용자가 요청을 중단했습니다.',
	'AJAX_ERROR_TEXT_TIMEOUT'	=> '요청 시간이 초과되었습니다. 다시 시도해 주세요.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> '요청에 문제가 발생하여 서버에서 잘못된 응답을 반환했습니다.',
	'ALLOWED'			=> '허용된',
	'ALL_FILES'			=> '모든 파일',
	'ALL_FORUMS'			=> '모든 포럼',
	'ALL_MESSAGES'			=> '모든 메시지',
	'ALL_POSTS'			=> '모든 게시물',
	'ALL_TIMES'			=> '모든 시간은 <span title="%2$s">%1$s</span>입니다.',
	'ALL_TOPICS'			=> '모든 주제',
	'ALT_TEXT'			=> '대체 텍스트',
	'AND'				=> '그리고',
	'ARE_WATCHING_FORUM'		=> '이 포럼의 새 게시물에 대한 알림을 받도록 구독했습니다.',
	'ARE_WATCHING_TOPIC'		=> '이 주제의 새 게시물에 대한 알림을 받도록 구독했습니다.',
	'ASCENDING'			=> '오름차순',
	'ATTACHMENTS'			=> '첨부파일',
	'ATTACHED_IMAGE_NOT_IMAGE'	=> '첨부하려는 이미지 파일이 유효하지 않습니다.',
	'AUTHOR'			=> '저자',
	'AUTH_NO_PROFILE_CREATED'	=> '사용자 프로필 생성에 실패했습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_ALREADY_LINKED'	=> '이 외부 서비스는 이미 다른 보드 계정과 연결되어 있습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'	=> '잘못된 데이터베이스 항목입니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'	=> 'OAuth 서비스 핸들러에 잘못된 서비스 유형이 제공되었습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_REQUEST'			=> 'OAuth 요청을 처리하는 중에 문제가 발생했습니다.',
	'AUTH_PROVIDER_OAUTH_RETURN_ERROR'			=> '외부 서비스가 잘못된 값을 반환했기 때문에 요청을 처리할 수 없습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'		=> 'OAuth 서비스가 생성되지 않음',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'			=> '비틀리',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'			=> '페이스북',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'			=> '구글',
	'AUTH_PROVIDER_OAUTH_SERVICE_TWITTER'			=> '트위터',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'		=> 'OAuth 토큰이 저장되지 않았습니다.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth 토큰이 잘못 저장되었습니다.',
	'AVATAR_DISALLOWED_CONTENT'	=> '업로드된 파일이 가능한 공격 벡터로 식별되어 업로드가 거부되었습니다.',
	'AVATAR_DISALLOWED_EXTENSION'	=> '확장자 <strong>%s</strong>가 허용되지 않기 때문에 이 파일을 표시할 수 없습니다.',
	'AVATAR_EMPTY_REMOTE_DATA'	=> '원격 데이터가 유효하지 않거나 손상되었기 때문에 지정된 아바타를 업로드할 수 없습니다.',
	'AVATAR_EMPTY_FILEUPLOAD'	=> '업로드한 아바타 파일이 비어 있습니다.',
	'AVATAR_INVALID_FILENAME'	=> '%s는 잘못된 파일 이름입니다.',
	'AVATAR_NOT_UPLOADED'		=> '아바타를 업로드할 수 없습니다.',
	'AVATAR_NO_TEMP_DIR'		=> '임시 폴더를 찾을 수 없거나 쓸 수 없습니다.',
	'AVATAR_NO_SIZE'		=> '연결된 아바타의 너비 또는 높이를 결정할 수 없습니다. 수동으로 입력하십시오.',
	'AVATAR_NO_UPLOAD_DIR'		=> '아바타 저장 경로가 존재하지 않거나 쓸 수 없습니다.',
	'AVATAR_NO_UPLOAD_PATH'		=> '아바타 업로드는 가능하나 아바타 저장경로가 설정되어 있지 않습니다.',
	'AVATAR_PARTIAL_UPLOAD'		=> '지정된 파일이 부분적으로만 업로드되었습니다.',
	'AVATAR_PHP_SIZE_NA'		=> '아바타의 파일 크기가 너무 큽니다.<br />php.ini에 설정된 최대 허용 파일 크기를 결정할 수 없습니다.',
	'AVATAR_PHP_SIZE_OVERRUN'	=> '아바타의 파일 크기가 너무 큽니다. 허용되는 최대 업로드 크기는 %1$d %2$s입니다.<br />이 값은 php.ini에 설정되며 재정의할 수 없습니다.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'	=> '요청 시간이 초과되어 지정된 아바타를 업로드할 수 없습니다.',
	'AVATAR_PHP_UPLOAD_STOPPED'	=> 'PHP 확장 프로그램이 파일 업로드를 중지했습니다.',
	'AVATAR_URL_INVALID'		=> '지정한 URL이 잘못되었습니다.',
	'AVATAR_URL_NOT_FOUND'		=> '지정한 파일을 찾을 수 없습니다.',
	'AVATAR_WRONG_FILESIZE'		=> '아바타의 파일 크기는 0에서 %1$d %2$s 사이여야 합니다.',
	'AVATAR_WRONG_SIZE'		=> '제출된 아바타는 폭 %5$s이고 높이가 %6$s입니다. 아바타는 폭이 %1$s 이상이고 높이가 %2$s 이상이어야 하며 폭이 %3$s, 높이가 %4$s 이하여야 합니다.',

	'BACK_TO_TOP'			=> '맨 위',
	'BACK_TO_PREV'			=> '이전 페이지로 돌아가기',
	'BAN_TRIGGERED_BY_EMAIL'	=> '당신의 이메일주소에 차단 조치가 내려졌습니다.',
	'BAN_TRIGGERED_BY_IP'		=> '당신의 IP 주소에 차단 조치가 내려졌습니다.',
	'BAN_TRIGGERED_BY_USER'		=> '당신의 사용자 이름이 차단되었습니다.',
	'BBCODE_GUIDE'			=> 'BBCode 가이드',
	'BCC'				=> 'BCC',
	'BIRTHDAYS'			=> '생일',
	'BOARD_BAN_PERM'		=> '이 보드에서 <strong>영구적으로</strong> 차단되었습니다.<br /><br />자세한 내용은 %2$s보드 관리자%3$s에게 문의하십시오.',
	'BOARD_BAN_REASON'		=> '차단 사유: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> '당신은 <strong>%1$s</strong>까지 이 게시판에서 차단되었습니다.<br /><br />자세한 내용은 %2$s게시판 관리자%3$s에게 문의하십시오.',
	'BOARD_DISABLE'			=> '죄송합니다. 현재 이 보드를 사용할 수 없습니다.',
	'BOARD_DISABLED'		=> '이 보드는 현재 비활성화되어 있습니다.',
	'BOARD_UNAVAILABLE'		=> '죄송합니다. 일시적으로 보드를 사용할 수 없습니다. 몇 분 후에 다시 시도해 주세요.',
	'BROWSING_FORUM'		=> '이 포럼을 탐색하는 사용자: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> '이 포럼을 탐색하는 사용자: %2$s 및 %1$d 손님',
		2	=> '이 포럼을 탐색하는 사용자들: %2$s 및 %1$d 손님들',
	),
	'BUTTON_DELETE'         => '삭제',
	'BUTTON_EDIT'		=> '편집',
	'BUTTON_FORUM_LOCKED'	=> '잠김',
	'BUTTON_INFORMATION'    => '정보',
	'BUTTON_NEW_TOPIC'	=> '새 주제',
	'BUTTON_PM'		=> 'PM',
	'BUTTON_PM_FORWARD'	=> '전달',
	'BUTTON_PM_NEW'		=> '새 PM',
	'BUTTON_PM_REPLY'	=> '답장',
	'BUTTON_PM_REPLY_ALL'	=> '모두에게 답장',
	'BUTTON_POST_REPLY'	=> '답장 게시',
	'BUTTON_QUOTE'		=> '인용',
	'BUTTON_REPORT'         => '보고',
	'BUTTON_TOPIC_LOCKED'	=> '잠김',
	'BUTTON_WARN'           => '경고',
	'BYTES'			=> '바이트',
	'BYTES_SHORT'		=> 'B',

	'CANCEL'		=> '취소',
	'CHANGE'		=> '변경',
	'CHANGE_FONT_SIZE'	=> '글꼴 크기 변경',
	'CHANGING_PREFERENCES'	=> '보드 기본 설정 변경',
	'CHANGING_PROFILE'	=> '프로필 설정 변경',
	'CHARACTERS'		=> array(
		1	=> '%d 문자',
		2	=> '%d 문자들',
	),
	'COLLAPSE_VIEW'			=> '보기 접기',
	'CLOSE_WINDOW'			=> '창 닫기',
	'CODE'				=> '코드',
	'COLOUR_SWATCH'			=> '색상 견본',
	'COLON'				=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// 목록을 단일 문자열로 결합하는 데 사용되는 쉼표, 적절한 경우 현지화된 쉼표 사용, 예: 표의 문자 또는 아랍어
	'CONFIRM'			=> '확인',
	'CONFIRM_CODE'			=> '확인 코드',
	'CONFIRM_CODE_EXPLAIN'	=> '표시된 그대로 코드를 입력하세요. 모든 문자는 대소문자를 구분하지 않습니다.',
	'CONFIRM_CODE_WRONG'	=> '입력한 확인 코드가 잘못되었습니다.',
	'CONFIRM_OPERATION'	=> '이 작업을 수행하겠습니까?',
	'CONFIRM_AVATAR_DELETE' => '이 아바타를 삭제하겠습니까?',
	'CONGRATULATIONS'	=> '축하',
	'CONNECTION_FAILED'	=> '연결 실패.',
	'CONNECTION_SUCCESS'	=> '연결 성공!',
	'CONTACT'		=> '연락',
	'CONTACT_USER'		=> '%s 연락처',
	'CONTACT_US'		=> '문의하기',
	'COOKIE_CONSENT_INFO'	=> '더 알아보기',
	'COOKIE_CONSENT_MSG'	=> '이 웹사이트는 당신이 당사 웹사이트에서 최상의 경험을 할 수 있도록 쿠키를 사용합니다.',
	'COOKIE_CONSENT_OK'	=> '알았어요!',
	'COOKIE_CONSENT_HREF'	=> 'http://cookiesandyou.com',
	'COOKIES_DELETED'	=> '모든 게시판 쿠키가 성공적으로 삭제되었습니다.',
	'CURRENT_TIME'		=> '현재 %s',

	'DAY'			=> '일',
	'DAYS'			=> '일',
	'DELETE'		=> '삭제',
	'DELETE_ALL'		=> '모두 삭제',
	'DELETE_COOKIES'	=> '쿠키 삭제',
	'DELETE_MARKED'		=> '표시된 것 삭제',
	'DELETE_POST'		=> '게시물 삭제',
	'DELIMITER'		=> '구분자',
	'DESCENDING'		=> '내림차순',
	'DISABLED'		=> '불가',
	'DISPLAY'		=> '표시',
	'DISPLAY_GUESTS'	=> '손님 표시',
	'DISPLAY_MESSAGES'	=> '이전 메시지 표시',
	'DISPLAY_POSTS'		=> '이전 게시물 표시',
	'DISPLAY_TOPICS'	=> '이전 주제 표시',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> '입력한 이메일 도메인에 유효한 MX 레코드가 없습니다.',
	'DOWNLOADED'		=> '다운로드됨',
	'DOWNLOADING_FILE'	=> '파일 다운로드 중',
	'DOWNLOAD_COUNTS'	=> array(
		0	=> '아직 다운로드되지 않음',
		1	=> '%d번 다운로드됨',	
		2	=> '%d번 다운로드됨',	
	),

	'EDIT_POST'				=> '게시물 수정',
	'ELLIPSIS'				=>	'…',
	'EMAIL'					=> '이메일', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'				=> '이메일 주소',
	'EMAIL_INVALID_EMAIL'			=> '입력하신 이메일 주소가 유효하지 않습니다.',
	'EMAIL_SMTP_ERROR_RESPONSE'		=> '<strong>Line %1$s</strong>에서 이메일을 보내는 데 문제가 발생했습니다. 응답: %2$s.',
	'EMPTY_SUBJECT'				=> '새 주제를 게시할 때 제목을 지정해야 합니다.',
	'EMPTY_MESSAGE_SUBJECT'			=> '새 메시지를 작성할 때 제목을 지정해야 합니다.',
	'ENABLED'				=> '사용',
	'ENCLOSURE'				=> '울 안',
	'ENTER_USERNAME'			=> '사용자 이름 입력',
	'ERR_CHANGING_DIRECTORY'		=> '디렉토리를 변경할 수 없습니다.',
	'ERR_CONNECTING_SERVER'			=> '서버에 연결하는 동안 오류가 발생했습니다.',
	'ERR_JAB_AUTH'				=> 'Jabber 서버에서 인증할 수 없습니다.',
	'ERR_JAB_CONNECT'			=> 'Jabber 서버에 연결할 수 없습니다.',
	'ERR_UNABLE_TO_LOGIN'			=> '지정된 사용자 이름 또는 암호가 올바르지 않습니다.',
	'ERR_UNWATCHING'			=> '구독을 취소하는 동안 오류가 발생했습니다.',
	'ERR_WATCHING'				=> '구독하는 동안 오류가 발생했습니다.',
	'ERR_WRONG_PATH_TO_PHPBB'		=> '지정된 phpBB 경로가 잘못된 것 같습니다.',
	'ERROR'					=> '오류',
	'EXPAND_VIEW'				=> '전개',
	'EXTENSION'				=> '확장',
	'EXTENSION_DISABLED'			=> '확장 프로그램 <strong>%s</strong>이(가) 활성화되지 않았습니다.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> '확장 프로그램 <strong>%s</strong>이(가) 비활성화되어 더 이상 표시할 수 없습니다.',
	'EXTENSION_DOES_NOT_EXIST'		=> '확장 프로그램 <strong>%s</strong>이(가) 존재하지 않습니다.',

	'FACEBOOK'		=> '페이스북',
	'FAQ'			=> '자주하는 질문',
	'FAQ_EXPLAIN'		=> '자주 묻는 질문',
	'FEATURE_NOT_AVAILABLE' => '요청한 기능은 이 게시판에서 사용할 수 없습니다.',
	'FILENAME'		=> '파일 이름',
	'FILESIZE'		=> '파일 크기',
	'FILEDATE'		=> '파일 날짜',
	'FILE_COMMENT'		=> '파일 댓글',
	'FILE_CONTENT_ERR'	=> '파일 내용을 읽을 수 없습니다: %s',
	'FILE_JSON_DECODE_ERR'	=> 'json 파일을 디코딩하지 못했습니다. %s',
	'FILE_NOT_FOUND'	=> '요청한 파일을 찾을 수 없습니다: %s',
	'FIND_USERNAME'		=> '회원 찾기',
	'FOLDER'		=> '폴더',
	'FORGOT_PASS'		=> '암호를 잊어버렸습니다',
	'FORM_INVALID'		=> '제출된 양식이 유효하지 않습니다. 다시 제출해 보세요.',
	'FORUM'			=> '포럼',
	'FORUMS'		=> '포럼',
	'FORUMS_MARKED'		=> '포럼이 읽은 것으로 표시되었습니다.',
	'FORUM_CAT'		=> '포럼 카테고리',
	'FORUM_INDEX'		=> '보드 인덱스',
	'FORUM_LINK'		=> '포럼 링크',
	'FORUM_LOCATION'	=> '포럼 위치',
	'FORUM_LOCKED'		=> '포럼 잠김',
	'FORUM_RULES'		=> '포럼 규칙',
	'FORUM_RULES_LINK'	=> '포럼 규칙을 보려면 여기를 클릭하십시오.',
	'FROM'			=> '에서',
	'FSOCK_DISABLED'	=> '<var>fsockopen</var> 기능이 비활성화되었거나 쿼리 중인 서버를 찾을 수 없기 때문에 작업을 완료할 수 없습니다.',
	'FSOCK_TIMEOUT'		=> '네트워크 스트림에서 읽는 동안 시간 초과가 발생했습니다.',

	'FILESYSTEM_CANNOT_CHANGE_FILE_GROUP'		=> '파일 그룹을 변경할 수 없습니다.',
	'FILESYSTEM_CANNOT_CHANGE_FILE_PERMISSIONS'	=> '파일 권한을 변경할 수 없습니다.',
	'FILESYSTEM_CANNOT_COPY_FILES'			=> '파일을 복사할 수 없습니다.',
	'FILESYSTEM_CANNOT_CREATE_SYMLINK'		=> 'symlink를 생성할 수 없습니다.',
	'FILESYSTEM_CANNOT_CREATE_DIRECTORY'		=> '디렉토리를 생성할 수 없습니다',
	'FILESYSTEM_CANNOT_DELETE_FILES'		=> '시스템에서 파일을 삭제할 수 없습니다',
	'FILESYSTEM_CANNOT_DUMP_FILE'			=> '파일에 덤프할 수 없습니다.',
	'FILESYSTEM_CANNOT_MIRROR_DIRECTORY'		=> '디렉터리를 미러링할 수 없습니다.',
	'FILESYSTEM_CANNOT_RENAME_FILE'			=> '시스템에서 파일 이름을 바꿀 수 없습니다.',
	'FILESYSTEM_CANNOT_TOUCH_FILES'			=> '파일을 만들거나 파일 타임스탬프를 변경할 수 없습니다.',

	'FTP_FSOCK_HOST'		=> 'FTP 호스트',
	'FTP_FSOCK_HOST_EXPLAIN'	=> '사이트를 연결하는 데 사용되는 FTP 서버입니다.',
	'FTP_FSOCK_PASSWORD'		=> 'FTP 암호',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'FTP 사용자 이름의 암호입니다.',
	'FTP_FSOCK_PORT'		=> 'FTP 포트',
	'FTP_FSOCK_PORT_EXPLAIN'	=> '서버에 연결하는 데 사용되는 포트입니다.',
	'FTP_FSOCK_ROOT_PATH'		=> 'phpBB 경로',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> '루트에서 phpBB 보드까지의 경로.',
	'FTP_FSOCK_TIMEOUT'		=> 'FTP 시간 초과',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'	=> '시스템이 서버의 응답을 기다리는 시간(초)입니다.',
	'FTP_FSOCK_USERNAME'		=> 'FTP 사용자 이름',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> '서버에 연결하는 데 사용되는 사용자 이름입니다.',

	'FTP_HOST'			=> 'FTP 호스트',
	'FTP_HOST_EXPLAIN'		=> '사이트를 연결하는 데 사용되는 FTP 서버입니다.',
	'FTP_PASSWORD'			=> 'FTP 암호',
	'FTP_PASSWORD_EXPLAIN'		=> 'FTP 사용자 이름의 암호입니다.',
	'FTP_PORT'			=> 'FTP 포트',
	'FTP_PORT_EXPLAIN'		=> '서버에 연결하는 데 사용되는 포트입니다.',
	'FTP_ROOT_PATH'			=> 'phpBB 경로',
	'FTP_ROOT_PATH_EXPLAIN'		=> '루트에서 phpBB 보드까지의 경로.',
	'FTP_TIMEOUT'			=> 'FTP 시간 초과',
	'FTP_TIMEOUT_EXPLAIN'		=> '시스템이 서버의 응답을 기다리는 시간(초)입니다.',
	'FTP_USERNAME'			=> 'FTP 사용자 이름',
	'FTP_USERNAME_EXPLAIN'		=> '서버에 연결하는 데 사용되는 사용자 이름입니다.',

	'GENERAL_ERROR'			=> '일반 오류',
	'GB'				=> 'GB',
	'GIB'				=> 'GiB',
	'GO'				=> '이동',
	'GOTO_FIRST_POST'		=> '첫 게시물로 이동',
	'GOTO_LAST_POST'		=> '마지막 게시물로 이동',
	'GOTO_PAGE'			=> '페이지로 이동',
	'GROUP'				=> '그룹',
	'GROUPS'			=> '그룹',
	'GROUP_ERR_TYPE'		=> '부적절한 그룹 유형이 지정되었습니다.',
	'GROUP_ERR_USERNAME'		=> '지정된 그룹 이름이 없습니다.',
	'GROUP_ERR_USER_LONG'		=> '그룹 이름은 60자를 초과할 수 없습니다. 지정된 그룹 이름이 너무 깁니다.',
	'GUEST'				=> '손님',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> '온라인에 손님 %d명 있습니다.',
		2	=> '온라인에 손님 %d명 있습니다.',
	),
	'GUEST_USERS_TOTAL'		=> array(
		1	=> '%d 손님',
		2	=> '%d 손님',
	),
	'G_ADMINISTRATORS'		=> '관리자',
	'G_BOTS'			=> '봇',
	'G_GUESTS'			=> '손님',
	'G_REGISTERED'			=> '등록 사용자',
	'G_REGISTERED_COPPA'		=> '등록된 COPPA 사용자',
	'G_GLOBAL_MODERATORS'		=> '글로벌 중재자',
	'G_NEWLY_REGISTERED'		=> '신규 등록 사용자',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d명의 숨겨진 사용자',
		2	=> '%d명의 숨겨진 사용자들',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d 숨김',
		2	=> '%d 숨김',
	),
	'HIDE_GUESTS'			=> '손님 숨기기',
	'HIDE_ME'			=> '이 세션에서 내 온라인 상태 숨기기',
	'HOURS'				=> '시간',
	'HOME'				=> '홈',

	'ICQ'				=> 'ICQ',
	'IF'				=> 'If',
	'IMAGE'				=> '이미지',
	'IMAGE_FILETYPE_INVALID'	=> 'mimetype %s에 대한 이미지 파일 유형 %d은(는) 지원되지 않습니다.',
	'IMAGE_FILETYPE_MISMATCH'	=> '이미지 파일 유형 불일치: 예상 확장자는 %1$s이지만 확장자는 %2$s입니다.',
	'IN'				=> '에',
	'INACTIVE'			=> '비활성',
	'INDEX'				=> '인덱스 페이지',
	'INFORMATION'			=> '정보',
	'INSECURE_REDIRECT'		=> '잠재적으로 안전하지 않은 URL로 리디렉션을 시도했습니다.',
	'INTERESTS'			=> '이해',
	'INVALID_DIGEST_CHALLENGE'	=> '부당한 다이제스트 챌린지입니다.',
	'INVALID_EMAIL_LOG'		=> '<strong>%s</strong> 잘못된 이메일 주소입니까?',
	'INVALID_FEED_ATTACHMENTS'	=> '선택한 피드가 잘못된 제약 조건이 있는 첨부 파일 가져오기를 시도했습니다.',
	'INVALID_PLURAL_RULE'		=> '당신의 IP %1$s은(는) 블랙리스트에 등록되어 차단되었습니다. 자세한 내용은 <a href="%2$s">%2$s</a>를 참조하십시오.',
	'IP'				=> 'IP',
	'IP_BLACKLISTED'		=> '선택한 복수 규칙이 유효하지 않습니다. 유효한 값은 0에서 15 사이의 정수입니다.',

	'JABBER'			=> 'Jabber',
	'JOINED'			=> '가입',
	'JUMP_PAGE'			=> '이동하려는 페이지 번호를 입력하세요.',
	'JUMP_TO'			=> '이동',
	'JUMP_TO_PAGE'			=> '페이지로 이동',
	'JUMP_TO_PAGE_CLICK'	=> '페이지로 이동하려면 클릭…',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'				=> '최근 게시물',
	'LAST_UPDATED'				=> '최근 업데이트',
	'LAST_VISIT'				=> '최근 방문',
	'LDAP_NO_LDAP_EXTENSION'		=> 'LDAP 확장을 사용할 수 없습니다.',
	'LDAP_NO_SERVER_CONNECTION'		=> 'LDAP 서버에 연결하는 동안 오류가 발생했습니다.',
	'LEGEND'				=> '범례',
	'LIVE_SEARCHES_NOT_ALLOWED'		=> '실시간 검색은 허용되지 않습니다.',
	'LOADING'				=> '로드 중',
	'LOCATION'				=> '위치',
	'LOCK_POST'				=> '잠금 게시물',
	'LOCK_POST_EXPLAIN'			=> '편집 방지',
	'LOCK_TOPIC'				=> '주제 잠금',
	'LOGIN'					=> '로그인',
	'LOGIN_CHECK_PM'			=> '비공개 메시지를 확인하려면 로그인하세요.',
	'LOGIN_CONFIRMATION'			=> '로그인 확인',
	'LOGIN_CONFIRM_EXPLAIN'			=> '무차별 대입 계정을 방지하기 위해 보드는 최대 로그인 실패 후 확인 코드를 입력하도록 요구합니다. 코드는 아래에 표시되어야 하는 이미지에 표시됩니다. 시각 장애가 있거나 이 코드를 읽을 수 없는 경우 %s보드 관리자%s에게 문의하십시오.', // unused
	'LOGIN_ERROR_ATTEMPTS'			=> '허용된 최대 로그인 시도 횟수를 초과했습니다. 사용자 이름과 암호 외에도 CAPTCHA 테스트를 통과해야 합니다.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'Apache에서 인증하지 않았습니다.',
'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST' => '존재하지 않는 OAuth 서비스가 요청되었습니다.',
	'LOGIN_ERROR_PASSWORD'			=> '잘못된 암호를 지정했습니다. 암호를 확인하고 다시 시도해 주세요. 문제가 계속되면 %s게시판 관리자%s에게 문의하십시오.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> '이 게시판의 소프트웨어를 업데이트할 때 암호를 변환할 수 없습니다. %s새 암호를 요청하십시오%s. 문제가 계속되면 %s게시판 관리자%s에게 문의하십시오.',
	'LOGIN_ERROR_USERNAME'			=> '잘못된 사용자 이름을 지정했습니다. 사용자 이름을 확인하고 다시 시도하십시오. 문제가 계속되면 %s게시판 관리자%s에게 문의하십시오.',
	'LOGIN_FORUM'			=> '이 포럼을 보거나 게시하려면 암호를 입력해야 합니다.',
	'LOGIN_INFO'			=> '로그인 하려면 회원가입을 하셔야 합니다. 가입하는 데 몇 분 안 걸리지만 향상된 기능을 제공합니다. 게시판 관리자는 등록 사용자에게 추가 권한을 부여할 수도 있습니다. 가입 전에 이용약관 및 관련 정책을 숙지하시기 바랍니다. 보드를 탐색할 때 포럼 규칙을 반드시 읽으십시오.',
	'LOGIN_VIEWFORUM'		=> '이 포럼을 보려면 게시판에 등록하고 로그인해야 합니다.',
	'LOGIN_EXPLAIN_EDIT'		=> '이 포럼에서 게시물을 편집하려면 등록 및 로그인해야 합니다.',
	'LOGIN_EXPLAIN_VIEWONLINE'	=> '온라인 목록을 보려면 등록 및 로그인해야 합니다.',
	'LOGIN_REQUIRED'		=> '이 작업을 수행하려면 로그인해야 합니다.',
	'LOGOUT'			=> '로그 아웃',
	'LOGOUT_USER'			=> '로그아웃 [ %s ]',
	'LOG_ME_IN'			=> '저장하기',

	'MAIN'			=> '기본',
	'MARK'			=> '표시',
	'MARK_ALL'		=> '모두 표시',
	'MARK_ALL_READ'		=> '모두 읽은 것으로 표시',
	'MARK_FORUMS_READ'	=> '읽은 포럼으로 표시',
	'MARK_READ'		=> '읽은 것으로 표시',
	'MARK_SUBFORUMS_READ'	=> '하위 포럼을 읽은 것으로 표시',
	'MB'			=> 'MB',
	'MIB'			=> 'MiB',
	'MCP'			=> '중재자 제어판',
	'MCP_SHORT'		=> 'MCP',
	'MEMBERLIST'		=> '회원',
	'MEMBERLIST_EXPLAIN'	=> '전체 회원 목록 보기',
	'MERGE'			=> '병합',
	'MERGE_POSTS'		=> '게시물 이동',
	'MERGE_TOPIC'		=> '주제 병합',
	'MESSAGE'		=> '메시지',
	'MESSAGES'		=> '메시지',
	'MESSAGES_COUNT'	=> array(
		0	=> '무제한 메시지',
		1	=> '%d 메시지',
		2	=> '%d 메시지',
	),
	'MESSAGE_BODY'			=> '메시지 본문',
	'MINUTES'			=> '분',
	'MODERATE'			=> '중재',
	'MODERATOR'			=> '중재자',
	'MODERATORS'			=> '중재자',
	'MODULE_NOT_ACCESS'		=> '모듈에 액세스할 수 없음',
	'MODULE_NOT_FIND'		=> '%s 모듈을 찾을 수 없습니다.',
	'MODULE_FILE_INCORRECT_CLASS'	=> '모듈 파일 %s에 올바른 클래스 [%s]가 포함되어 있지 않습니다.',
	'MONTH'				=> '월',
	'MOVE'				=> '이동',

	'NA'				=> 'N/A',
	'NEWEST_USER'			=> '최근 회원 <strong>%s</strong>',
	'NEW_MESSAGE'			=> '새 메시지',
	'NEW_MESSAGES'			=> '새 메시지',
	'NEW_POST'			=> '새 게시물' , // Not used anymore
	'NEW_POSTS'			=> '새 게시물',	 // Not used anymore
	'NEXT'				=> '다음',		 // Used in pagination
	'NEXT_STEP'			=> '다음',
	'NEVER'				=> '절대 안',
	'NO'				=> '아니요',
	'NO_NOTIFICATIONS'		=> '알림이 없습니다.',
	'NOT_ALLOWED_MANAGE_GROUP'	=> '이 그룹을 관리할 권한이 없습니다.',
	'NOT_AUTHORISED'		=> '이 영역에 액세스할 수 있는 권한이 없습니다.',
	'NOT_WATCHING_FORUM'		=> '더 이상 이 포럼의 업데이트를 구독하지 않습니다.',
	'NOT_WATCHING_TOPIC'		=> '더 이상 이 주제를 구독하지 않습니다.',
	'NOTIFICATIONS'			=> '알림',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '북마크된 주제에서 %1$s의 <strong>답글</strong>:',
	),
	'NOTIFICATION_FORUM'			=> '<em>포럼:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '%1$s의 <strong>그룹 요청</strong>은 %2$s 그룹에 가입하도록 합니다.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '%1$s 그룹에 대한 <strong>그룹 요청이 승인되었습니다</strong>.',
	'NOTIFICATION_METHOD_INVALID'		=> '"%s" 방법은 유효한 알림 방법을 참조하지 않습니다.',
	'NOTIFICATION_PM'			=> '%1$s의 <strong>비공개 메시지</strong>:',
	'NOTIFICATION_POST'			=> array(
		1	=> '주제에 대한 %1$s의 <strong>답글</strong>:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>게시물 승인됨</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>비승인된 게시물</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '%1$s의 <strong>사후 승인</strong> 요청:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '%1$s가 <strong>인용</strong>:',
	),
	'NOTIFICATION_REFERENCE'		=> '"%1$s"',
	'NOTIFICATION_REASON'			=> '<em>이유:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'		=> '%1$s에 의해 보고된 <strong>비공개 메시지</strong>:',
	'NOTIFICATION_REPORT_PM_CLOSED'		=> '<strong>비공개 메시지 보고서 마감</strong>: %1$s:',
	'NOTIFICATION_REPORT_POST'		=> '%1$s님이 <strong>신고한 소식</strong>:',
	'NOTIFICATION_REPORT_CLOSED'		=> '다음 항목에 대해 %1$s가 <strong>보고서를 닫았습니다</strong>.',
	'NOTIFICATION_TOPIC'			=> '%1$s의 <strong>새 주제</strong>:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>승인된 주제</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>비승인된 주제</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '%1$s의 <strong>주제 승인</strong> 요청:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> '알림 유형 "%s"이(가) 파일 시스템에서 누락되었습니다.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '비활성화되었거나 새로 등록된 사용자의 <strong>활성화 필요</strong>: “%1$s”',
	// Used in conjunction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> '다른 사람',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '기타 %d명',
	),
	'NOTIFY_ADMIN'			=> '게시판 관리자나 웹마스터에게 알려주십시오.',
	'NOTIFY_ADMIN_EMAIL'		=> '게시판 관리자나 웹마스터에게 알려주세요: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> '이 파일에 액세스할 수 없습니다.',
	'NO_ACTION'			=> '지정된 작업이 없습니다.',
	'NO_ADMINISTRATORS'		=> '관리자가 없습니다.',
	'NO_AUTH_ADMIN'			=> '관리 권한이 없으므로 관리 제어판에 대한 액세스가 허용되지 않습니다.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> '다른 사용자로 재인증할 수 없습니다.',
	'NO_AUTH_OPERATION'		=> '이 작업을 완료하는 데 필요한 권한이 없습니다.',
	'NO_AVATARS'			=> '현재 사용할 수 있는 아바타가 없습니다.',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'smtp 호스트에 연결할 수 없습니다: %1$s: %2$s',
	'NO_BIRTHDAYS'			=> '오늘은 생일이 없습니다',
	'NO_EMAIL_MESSAGE'		=> '이메일 메시지가 비어 있습니다.',
	'NO_EMAIL_RESPONSE_CODE'	=> '메일 서버 응답 코드를 가져올 수 없습니다.',
	'NO_EMAIL_SUBJECT'		=> '이메일 제목이 지정되지 않았습니다.',
	'NO_FORUM'			=> '선택한 포럼이 존재하지 않습니다.',
	'NO_FORUMS'			=> '이 게시판에는 포럼이 없습니다.',
	'NO_GROUP'			=> '요청한 사용자 그룹이 존재하지 않습니다.',
	'NO_GROUP_MEMBERS'		=> '이 그룹에는 현재 회원이 없습니다.',
	'NO_IPS_DEFINED'		=> '정의된 IP 주소 또는 호스트 이름이 없습니다.',
	'NO_MEMBERS'			=> '이 검색 기준에 대한 회원이 없습니다.',
	'NO_MESSAGES'			=> '메시지 없음',
	'NO_MODE'			=> '지정된 모드가 없습니다.',
	'NO_MODERATORS'			=> '중재자 없음.',
	'NO_NEW_MESSAGES'		=> '새 메시지 없음',
	'NO_NEW_POSTS'			=> '새 게시물 없음',	// Not used anymore
	'NO_ONLINE_USERS'		=> '등록된 사용자가 없습니다.',
	'NO_POSTS'			=> '게시물이 없습니다',
	'NO_POSTS_TIME_FRAME'		=> '선택한 기간 동안 이 주제 내에 게시물이 없습니다.',
	'NO_FEED_ENABLED'		=> '이 게시판에서는 피드를 사용할 수 없습니다.',
	'NO_FEED'			=> '요청한 피드를 사용할 수 없습니다.',
	'NO_STYLE_DATA'			=> 'user_style %s에 대한 스타일 데이터를 가져올 수 없고 user_id %s에 대해 설정할 수 없습니다.',
	'NO_STYLE_CFG'			=> '다음에 대한 스타일 구성 파일을 가져올 수 없습니다: %s',
	'NO_SUBJECT'			=> '지정된 주제가 없습니다.',	// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> '지정된 검색 백엔드가 없습니다.',
	'NO_SUPPORTED_AUTH_METHODS'	=> '지원되는 인증 방법이 없습니다.',
	'NO_TOPIC'			=> '요청한 주제가 존재하지 않습니다.',
	'NO_TOPIC_FORUM'		=> '주제 또는 포럼이 더 이상 존재하지 않습니다.',
	'NO_TOPICS'			=> '이 포럼에는 주제나 게시물이 없습니다.',
	'NO_TOPICS_TIME_FRAME'		=> '선택한 기간 동안 이 포럼에 주제가 없습니다.',
	'NO_UNREAD_POSTS'		=> '읽지 않은 게시물 없음',
	'NO_UPLOAD_FORM_FOUND'		=> '업로드가 시작되었지만 유효한 파일 업로드 양식을 찾을 수 없습니다.',
	'NO_USER'			=> '요청한 사용자가 존재하지 않습니다.',
	'NO_USERS'			=> '요청한 사용자가 존재하지 않습니다.',
	'NO_USER_SPECIFIED'		=> '사용자 이름이 지정되지 않았습니다.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '첨부 파일 %d개',
		2	=> '첨부 파일 %d개',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> '대기열에 게시물 없음',		// 0
		1			=> '대기열에 있는 게시물 1개',	// 1
		2			=> '대기열에 있는 게시물 %d개',	// 2+
	),

	'OCCUPATION'		=> '직업',
	'OFFLINE'		=> '오프라인',
	'ONLINE'		=> '온라인',
	'ONLINE_BUDDIES'	=> '온라인 친구',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'	=> array(
		1	=> '총 <strong>%1$d</strong>명 온라인 사용자 :: %2$s 및 %3$s',
		2	=> '총 <strong>%1$d</strong>명 온라인 사용자 :: %2$s 및 %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> '총 <strong>%1$d</strong>명 온라인 사용자 :: %2$s, %3$s 및 %4$s',
		2	=> '총 <strong>%1$d</strong>명 온라인 사용자 :: %2$s, %3$s 및 %4$s',
	),
	'OPTIONS'			=> '옵션',

	'PAGE_NOT_FOUND'		=> '요청하신 페이지를 찾을 수 없습니다.',
	'PAGE_OF'			=> '페이지 <strong>%1$d</strong> / <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> '페이지 %s',
	'PASSWORD'			=> '암호',
	'PIXEL'				=> '픽셀',
	'PIXELS'			=> array(
		1	=> '%d 픽셀',
		2	=> '%d 픽셀',
	),
	'PLEASE_WAIT'			=> '기다리세요.',
	'PM'				=> '개인메시지',
	'PM_REPORTED'			=> '보고서를 보려면 클릭하세요.',
	'POSTING_MESSAGE'		=> '%s에 메시지 게시 중',
	'POSTING_PRIVATE_MESSAGE'	=> '개인 메시지 작성',
	'POST'				=> '게시',
	'POST_ANNOUNCEMENT'		=> '발표',
	'POST_STICKY'			=> '어려운',
	'POSTED'			=> '게시됨',
	'POSTED_IN_FORUM'		=> '포럼에 씀',
	'POSTED_ON_DATE'		=> '글 쓴 날',
	'POSTS'				=> '게시물',
	'POSTS_UNAPPROVED'		=> '이 주제의 게시물이 하나 이상 승인되지 않았습니다.',
	'POSTS_UNAPPROVED_FORUM'	=> '이 포럼에서 하나 이상의 게시물이 승인되지 않았습니다.',
	'POST_BY_AUTHOR'		=> '글쓴이',
	'POST_BY_FOE'			=> '현재 무시 목록에 있는 <strong>%1$s</strong>님이 이 게시물을 작성했습니다.',
	'POST_DISPLAY'			=> '이 게시물 표시',
	'POST_DAY'			=> '하루 %.2f 게시물',
	'POST_DELETED_ACTION'	=> '삭제된 게시물:',
	'POST_DELETED'			=> '이 게시물은 삭제되었습니다.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong>이(가) %3$s에 <strong>%1$s</strong>의 게시물을 삭제했습니다.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong>이(가) 다음과 같은 이유로 %3$s에 <strong>%1$s</strong>의 게시물을 삭제했습니다. %4$s',
	'POST_DETAILS'			=> '게시물 세부정보',
	'POST_NEW_TOPIC'		=> '새 주제 게시',
	'POST_PCT'			=> '모든 게시물의 %.2f%%',
	'POST_PCT_ACTIVE'		=> '사용자 게시물의 %.2f%%',
	'POST_PCT_ACTIVE_OWN'	=> '게시물의 %.2f%%',
	'POST_REPLY'			=> '답글 게시',
	'POST_REPORTED'			=> '보고서를 보려면 클릭하세요.',
	'POST_SUBJECT'			=> '게시물 제목',
	'POST_TIME'			=> '게시 시간',
	'POST_TOPIC'			=> '새 주제 게시',
	'POST_UNAPPROVED_ACTION'	=> '승인 대기 중인 게시물:',
	'POST_UNAPPROVED'		=> '이 게시물은 승인되지 않았습니다.',
	'POST_UNAPPROVED_EXPLAIN'	=> '이 게시물은 중재자가 승인할 때까지 다른 사용자에게 표시되지 않습니다.',
	'POWERED_BY'			=> '%s 제공',

	'QUOTE'				=> '인용',

	'PREVIEW'			=> '미리보기',
	'PREVIOUS'			=> '이전의',		// Used in pagination
	'PREVIOUS_STEP'			=> '이전의',
	'PRIVACY'			=> '개인정보 정책',
	'PRIVACY_LINK'			=> '개인정보 보호',
	'PRIVATE_MESSAGE'		=> '비공개 메시지',
	'PRIVATE_MESSAGES'		=> '비공개 메시지',
	'PRIVATE_MESSAGING'		=> '비공개 메시지',
	'PROFILE'			=> '사용자 제어판',

	'QUICK_LINKS'			=> '빠른 링크',

	'RANK'				=> '계급',
	'READING_FORUM'			=> '%s에서 주제 보기',
	'READING_GLOBAL_ANNOUNCE'	=> '글로벌 발표 읽기',
	'READING_LINK'			=> '다음 포럼 링크 %s',
	'READING_TOPIC'			=> '%s에서 주제 읽기',
	'READ_PROFILE'			=> '프로필',
	'REASON'			=> '이유',
	'RECORD_ONLINE_USERS'		=> '가장 많은 온라인 사용자는 %2$s에 <strong>%1$s</strong>명 이었습니다.',
	'REDIRECT'			=> '리디렉션',
	'REDIRECTS'			=> '총 리디렉션',
	'REGISTER'			=> '등록',
	'REGISTERED_USERS'		=> '등록 사용자들:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'		=> array(
		1	=> '%1$d명 등록 사용자와 %2$s 온라인이 있습니다.',
		2	=> '등록된 사용자 %1$d명과 온라인 %2$s명이 있습니다.',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d 등록됨',
		2	=> '%d 등록됨',
	),
	'REMOVE'			=> '삭제',
	'REMOVE_INSTALL'		=> '보드를 사용하기 전에 설치 디렉토리를 삭제, 이동 또는 이름 변경하십시오. 이 디렉터리가 여전히 존재하면 관리 제어판(ACP)에만 액세스할 수 있습니다.',
	'REPLIES'			=> '답글',
	'REPLY_WITH_QUOTE'		=> '인용문으로 회신',
	'REPLYING_GLOBAL_ANNOUNCE'	=> '글로벌 발표에 회신',
	'REPLYING_MESSAGE'		=> '%s의 메시지에 회신하는 중',
	'REPORT_BY'			=> '보고자',
	'REPORT_POST'			=> '이 게시물 신고',
	'REPORTING_POST'		=> '신고글',
	'RESEND_ACTIVATION'		=> '활성화 이메일 재전송',
	'RESET'				=> '초기화',
	'RESTORE_PERMISSIONS'		=> '권한 복원',
	'RETURN_INDEX'			=> '%인덱스 페이지로 돌아가기%s',
	'RETURN_FORUM'			=> '%마지막으로 방문한 포럼으로 돌아가기%s',
	'RETURN_PAGE'			=> '%이전 페이지로 돌아가기%s',
	'RETURN_TOPIC'			=> '%마지막으로 방문한 주제로 돌아가기%s',
	'RETURN_TO'			=> '"%s"로 돌아가기',
	'RETURN_TO_INDEX'		=> '게시판 색인으로 돌아가기',

	'ROUTE_NOT_FOUND'		=> '요청한 경로 "%s"을(를) 찾을 수 없습니다.',
	'ROUTE_INVALID_MISSING_PARAMS'	=> '경로 "%s"에 대해 전달된 매개 변수가 잘못되었거나 누락되었습니다.',

	'FEED'				=> '피드',
	'FEED_NEWS'			=> '소식',
	'FEED_TOPICS_ACTIVE'		=> '활성 주제',
	'FEED_TOPICS_NEW'		=> '새 주제',
	'RULES_ATTACH_CAN'		=> '이 포럼에 첨부파일을 게시할 수 <strong>있습니다</strong>',
	'RULES_ATTACH_CANNOT'		=> '이 포럼에 첨부파일을 게시할 수 <strong>없습니다</strong>.',
	'RULES_DELETE_CAN'		=> '이 포럼에서 게시물을 삭제할 수 <strong>있습니다</strong>.',
	'RULES_DELETE_CANNOT'		=> '이 포럼에서 게시물을 삭제할 수 <strong>없습니다</strong>.',
	'RULES_DOWNLOAD_CAN'		=> '이 포럼에서 첨부파일을 다운로드할 수 <strong>있습니다</strong>',
	'RULES_DOWNLOAD_CANNOT'		=> '이 포럼에서 첨부파일을 다운로드할 수 <strong>없습니다</strong>.',
	'RULES_EDIT_CAN'		=> '이 포럼에서 게시물을 수정할 수 <strong>있습니다</strong>.',
	'RULES_EDIT_CANNOT'		=> '이 포럼에서 게시물을 수정할 수 <strong>없습니다</strong>.',
	'RULES_LOCK_CAN'		=> '이 포트에서 주제를 잠글 수 <strong>있습니다</strong>.',
	'RULES_LOCK_CANNOT'		=> '이 포럼에서 주제를 잠글 수 <strong>없습니다</strong>.',
	'RULES_POST_CAN'		=> '이 포럼에 새 주제를 게시할 수 <strong>있습니다</strong>',
	'RULES_POST_CANNOT'		=> '이 포럼에 새 주제를 게시할 수 <strong>없습니다</strong>.',
	'RULES_REPLY_CAN'		=> '이 포럼의 주제에 답글을 달 수 <strong>있습니다</strong>.',
	'RULES_REPLY_CANNOT'		=> '이 포럼의 주제에 답변할 수 <strong>없습니다</strong>.',
	'RULES_VOTE_CAN'		=> '이 포럼의 설문조사에 투표할 수</strong>있습니다</strong>.',
	'RULES_VOTE_CANNOT'		=> '이 포럼의 설문조사에 투표할 수 <strong>없습니다</strong>.',

	'SEARCH'			=> '검색',
	'SEARCH_MINI'			=> '검색…',
	'SEARCH_ADV'			=> '고급 검색',
	'SEARCH_ADV_EXPLAIN'		=> '고급 검색 옵션 보기',
	'SEARCH_KEYWORDS'		=> '키워드 검색',
	'SEARCHING_FORUMS'		=> '포럼 검색',
	'SEARCH_ACTIVE_TOPICS'		=> '활성 주제',
	'SEARCH_FOR'			=> '검색',
	'SEARCH_FORUM'			=> '이 포럼 검색…',
	'SEARCH_NEW'			=> '새 게시물',
	'SEARCH_POSTS_BY'		=> '게시물 검색 기준',
	'SEARCH_SELF'			=> '당신의 게시물',
	'SEARCH_TOPIC'			=> '이 주제 검색…',
	'SEARCH_UNANSWERED'		=> '답변되지 않은 주제',
	'SEARCH_UNREAD'			=> '읽지 않은 게시물',
	'SEARCH_USER_POSTS'		=> '사용자 게시물 검색',
	'SECONDS'			=> '초',
	'SEE_ALL'			=> '모두 보기',
	'SELECT'			=> '선택',
	'SELECT_ALL_CODE'		=> '모두 선택',
	'SELECT_DESTINATION_FORUM'	=> '대상 포럼을 선택하세요.',
	'SELECT_FORUM'			=> '포럼 선택',
	'SEND_EMAIL'			=> '이메일 보내기',	// Used for submit buttons
	'SEND_EMAIL_USER'		=> '%s에게 이메일 보내기',
	'SEND_PRIVATE_MESSAGE'		=> '개인 메시지 보내기',
	'SETTINGS'			=> '설정',
	'SIGNATURE'			=> '서명',
	'SKIP'				=> '콘텐츠로 건너뛰기',
	'SKYPE'				=> '스카이프',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP 서버는 인증을 지원하지 않습니다.',
	'SORRY_AUTH_READ'		=> '이 포럼을 읽을 수 있는 권한이 없습니다.',
	'SORRY_AUTH_READ_TOPIC'		=> '이 항목을 읽을 수 있는 권한이 없습니다.',
	'SORRY_AUTH_VIEW_ATTACH'	=> '이 첨부 파일을 다운로드할 권한이 없습니다.',
	'SORT_BY'			=> '정렬 기준',
	'SORT_DIRECTION'		=> '방향',
	'SORT_JOINED'			=> '가입일',
	'SORT_LOCATION'			=> '위치',
	'SORT_OPTIONS'			=> '표시 및 정렬 옵션',
	'SORT_RANK'			=> '순위',
	'SORT_POSTS'			=> '게시물',
	'SORT_TOPIC_TITLE'		=> '주제 제목',
	'SORT_USERNAME'			=> '사용자 이름',
	'SPLIT_TOPIC'			=> '주제 나누기',
	'SQL_ERROR_OCCURRED'		=> '이 페이지를 가져오는 동안 SQL 오류가 발생했습니다. 이 문제가 지속되면 %s보드 관리자%s에게 문의하십시오.',
	'STATISTICS'			=> '통계',
	'START_WATCHING_FORUM'		=> '포럼 구독',
	'START_WATCHING_TOPIC'		=> '주제 구독',
	'STOP_WATCHING_FORUM'		=> '포럼 구독 취소',
	'STOP_WATCHING_TOPIC'		=> '주제 구독 취소',
	'STRING_LIST_MULTI'		=> '%1$s 및 %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s 및 %2$s',
	'SUBFORUM'			=> '서브포럼',
	'SUBFORUMS'			=> '서브포럼',
	'SUBJECT'			=> '주제',
	'SUBMIT'			=> '제출',

	'TB'				=> 'TB',
	'TERMS_LINK'		=> '약관',
	'TERMS_USE'		=> '이용약관',
	'TEST_CONNECTION'	=> '테스트 연결',
	'THE_TEAM'			=> '팀',
	'TIB'				=> 'TiB',
	'TIME'				=> '시간',
	'TIMEOUT_PROCESSING_REQ'	=> '요청 시간이 초과되었습니다.',

	'TOO_LARGE'			=> '입력한 값이 너무 큽니다.',
	'TOO_LARGE_MAX_RECIPIENTS'	=> '입력한 <strong>비공개 메시지당 허용되는 최대 수신자 수</strong> 설정 값이 너무 큽니다.',

	'TOO_LONG'			=> '입력한 값이 너무 깁니다.',

	'TOO_LONG_CONFIRM_CODE'		=> '입력한 확인 코드가 너무 깁니다.',
	'TOO_LONG_DATEFORMAT'		=> '입력한 날짜 형식이 너무 깁니다.',
	'TOO_LONG_JABBER'		=> '입력한 Jabber 계정 이름이 너무 깁니다.',
	'TOO_LONG_NEW_PASSWORD'		=> '입력한 암호가 너무 깁니다.',
	'TOO_LONG_PASSWORD_CONFIRM'	=> '입력한 암호 확인이 너무 깁니다.',
	'TOO_LONG_USER_PASSWORD'	=> '입력한 암호가 너무 깁니다.',
	'TOO_LONG_USERNAME'		=> '입력한 사용자 이름이 너무 깁니다.',
	'TOO_LONG_EMAIL'		=> '입력한 이메일 주소가 너무 깁니다.',

	'TOO_MANY_VOTE_OPTIONS'		=> '너무 많은 옵션에 투표하려고 했습니다.',

	'TOO_SHORT'			=> '입력한 값이 너무 짧습니다.',

	'TOO_SHORT_CONFIRM_CODE'	=> '입력한 확인 코드가 너무 짧습니다.',
	'TOO_SHORT_DATEFORMAT'		=> '입력한 날짜 형식이 너무 짧습니다.',
	'TOO_SHORT_JABBER'		=> '입력한 Jabber 계정 이름이 너무 짧습니다.',
	'TOO_SHORT_NEW_PASSWORD'	=> '입력한 암호가 너무 짧습니다.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> '입력한 암호 확인이 너무 짧습니다.',
	'TOO_SHORT_USER_PASSWORD'	=> '입력한 암호가 너무 짧습니다.',
	'TOO_SHORT_USERNAME'		=> '입력한 사용자 이름이 너무 짧습니다.',
	'TOO_SHORT_EMAIL'		=> '입력한 이메일 주소가 너무 짧습니다.',
	'TOO_SHORT_EMAIL_CONFIRM'	=> '입력한 이메일 주소 확인이 너무 짧습니다.',
	'TOO_SMALL'			=> '입력한 값이 너무 작습니다.',
	'TOO_SMALL_MAX_RECIPIENTS'	=> '입력한 <strong>비공개 메시지당 허용되는 최대 수신자 수</strong> 설정 값이 너무 작습니다.',

	'TOPIC'			=> '주제',
	'TOPICS'		=> '주제',
	'TOPICS_UNAPPROVED'	=> '이 포럼에서 하나 이상의 주제가 승인되지 않았습니다.',
	'TOPIC_ICON'		=> '주제 아이콘',
	'TOPIC_LOCKED'		=> '이 주제는 잠겨 있으므로 게시물을 수정하거나 더 이상 답글을 달 수 없습니다.',
	'TOPIC_LOCKED_SHORT'	=> '주제 잠김',
	'TOPIC_MOVED'		=> '이동된 주제',
	'TOPIC_REVIEW'		=> '주제 검토',
	'TOPIC_TITLE'		=> '주제 제목',
	'TOPIC_UNAPPROVED'	=> '이 주제는 승인되지 않았습니다.',
	'TOPIC_UNAPPROVED_FORUM'	=> array(
		1	=> '승인 대기 중인 주제',
		2	=> '승인 대기 중인 주제',
	),
	'TOPIC_DELETED'		=> '이 주제는 삭제되었습니다.',
	'TOTAL_ATTACHMENTS'	=> '파일 첨부',
	'TOTAL_LOGS'		=> array(
		1	=> '%d 로그',
		2	=> '%d 로그',
	),
	'TOTAL_PMS'		=> array(
		1	=> '총 %d 개인 메시지',
		2	=> '총 %d개의 비공개 메시지',
	),
	'TOPIC_POLL'		=> '이 주제에는 설문조사가 있습니다.',
	'TOTAL_POSTS'		=> '총 게시물',
	'TOTAL_POSTS_COUNT'	=> array(
		1	=> '총 게시물 <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> '이 주제는 신고되었습니다.',
	'TOTAL_TOPICS'		=> array(
		1	=> '총 주제 <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		1	=> '총 회원 <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> '추적된 PHP 오류: %s',
	'TWITTER'			=> '트위터',

	'UNABLE_GET_IMAGE_SIZE'	=> '이미지의 크기를 결정할 수 없습니다. 입력한 URL이 올바른지 확인하십시오.',
	'UNABLE_TO_DELIVER_FILE'=> '파일을 전달할 수 없습니다.',
	'UNKNOWN_BROWSER'		=> '알 수 없는 브라우저',
	'UNMARK_ALL'			=> '모두 표시 해제',
	'UNREAD_MESSAGES'		=> '읽지 않은 메시지',
	'UNREAD_POST'			=> '읽지 않은 게시물',
	'UNREAD_POSTS'			=> '읽지 않은 게시물',
	'UNWATCH_FORUM_CONFIRM'		=> '이 포럼에서 구독을 취소하시겠습니까?',
	'UNWATCH_FORUM_DETAILED'	=> '"%s" 포럼에서 구독을 취소하시겠습니까?',
	'UNWATCH_TOPIC_CONFIRM'		=> '이 주제의 구독을 취소하시겠습니까?',
	'UNWATCH_TOPIC_DETAILED'	=> '주제 "%s"에서 구독을 취소하시겠습니까?',
	'UNWATCHED_FORUMS'		=> '선택한 포럼에 더 이상 가입되어 있지 않습니다.',
	'UNWATCHED_TOPICS'		=> '선택한 주제를 더 이상 구독하지 않습니다.',
	'UNWATCHED_FORUMS_TOPICS'	=> '선택한 주제를 더 이상 구독하지 않습니다.',
	'UPDATE'			=> '업데이트',
	'UPLOAD_IN_PROGRESS'	=> '현재 업로드가 진행 중입니다.',
	'URL_REDIRECT'		=> '브라우저가 메타 리디렉션 %s을(를) 지원하지 않는 경우 여기를 클릭하여 %s 리디렉션하십시오.',
	'USERGROUPS'		=> '그룹',
	'USERNAME'		=> '사용자 이름',
	'USERNAMES'		=> '사용자 이름',
	'USER_AVATAR'		=> '사용자 아바타',
	'USER_CANNOT_READ'	=> '이 포럼에서 게시물을 읽을 수 없습니다.',
	'USER_POSTS'		=> array(
		1	=> '%d 게시물',
		2	=> '%d 게시물',
	),
	'USERS'				=> '사용자',
	'USE_PERMISSIONS'		=> '사용자 권한 테스트',

	'USER_NEW_PERMISSION_DISALLOWED'	=> '이 기능을 사용할 권한이 없습니다. 방금 여기에 등록했을 수 있으며 이 기능을 사용하려면 토론에 더 많이 참여해야 할 수 있습니다.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// 날짜 형식 드롭다운에서 사용됨, 예: "Today, 13:37 / 01 Jan 2007, 13:37" ... 상대 날짜를 달력 날짜와 결합
	'VIEWED'					=> '조회됨',
	'VIEWED_COUNTS'		=> array(
		0	=> '아직 안 봄',
		1	=> '%d번 조회함',
		2	=> '%d번 조회함',
	),
	'VIEWING_CONTACT_ADMIN'		=> '연락처 페이지 보기',
	'VIEWING_FAQ'			=> 'FAQ 보기',
	'VIEWING_MEMBERS'		=> '회원정보 보기',
	'VIEWING_ONLINE'		=> '온라인 상태인 사람 보기',
	'VIEWING_MCP'			=> '진행자 제어판 보기',
	'VIEWING_MEMBER_PROFILE'	=> '회원 프로필 보기',
	'VIEWING_PRIVATE_MESSAGES'	=> '비공개 메시지 보기',
	'VIEWING_REGISTER'		=> '계정 등록',
	'VIEWING_UCP'			=> '사용자 제어판 보기',
	'VIEWS'				=> '보기',
	'VIEW_BOOKMARKS'		=> '북마크 보기',
	'VIEW_FORUM_LOGS'		=> '로그 보기',
	'VIEW_LATEST_POST'		=> '최신 게시물 보기',
	'VIEW_NEWEST_POST'		=> '읽지 않은 첫 번째 게시물 보기',
	'VIEW_NOTES'			=> '사용자 메모 보기',
	'VIEW_ONLINE_TIMES'		=> array(
		1	=> '지난 %d분 동안 활동한 사용자 기준',
		2	=> '지난 %d분 동안 활동한 사용들 기준',
	),
	'VIEW_TOPIC'			=> '주제 보기',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> '발표: ',
	'VIEW_TOPIC_GLOBAL'		=> '글로벌 발표: ',
	'VIEW_TOPIC_LOCKED'		=> '잠김: ',
	'VIEW_TOPIC_LOGS'		=> '로그 보기',
	'VIEW_TOPIC_MOVED'		=> '이동: ',
	'VIEW_TOPIC_POLL'		=> '투표: ',
	'VIEW_TOPIC_STICKY'		=> '어려운: ',
	'VISIT_WEBSITE'			=> '웹사이트 방문',

	'WARNINGS'			=> '경고',
	'WARN_USER'			=> '사용자에게 경고',
	'WATCH_FORUM_CONFIRM'	=> '이 포럼을 구독하시겠습니까?',
	'WATCH_FORUM_DETAILED'	=> '"%s" 포럼을 구독하시겠습니까?',
	'WATCH_TOPIC_CONFIRM'	=> '이 주제를 구독하시겠습니까?',
	'WATCH_TOPIC_DETAILED'	=> '"%s" 주제를 구독하시겠습니까?',
	'WELCOME_SUBJECT'	=> '%s 포럼에 오신 것을 환영합니다',
	'WEBSITE'			=> '웹사이트',
	'WHOIS'				=> '후이즈',
	'WHO_IS_ONLINE'		=> '온라인 상태인 사람',
	'WRONG_PASSWORD'	=> '잘못된 암호를 입력했습니다.',

	'WRONG_DATA_COLOUR'		=> '입력한 색상 값이 잘못되었습니다.',
	'WRONG_DATA_JABBER'		=> '입력한 이름은 유효한 Jabber 계정 이름이 아닙니다.',
	'WRONG_DATA_LANG'		=> '지정한 언어가 유효하지 않습니다.',
	'WRONG_DATA_POST_SD'		=> '지정한 게시물 정렬 방향이 유효하지 않습니다.',
	'WRONG_DATA_POST_SK'		=> '지정한 게시물 정렬 옵션이 유효하지 않습니다.',
	'WRONG_DATA_TOPIC_SD'		=> '지정한 주제 정렬 방향이 유효하지 않습니다.',
	'WRONG_DATA_TOPIC_SK'		=> '지정한 주제 정렬 옵션이 유효하지 않습니다.',
	'WROTE'				=> '씀',

	'YAHOO'				=> '야후 메신저',
	'YOUTUBE'			=> '유튜브',
	'YEAR'				=> '년',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'			=> '예',
	'YOU_LAST_VISIT'	=> '마지막 방문: %s',

	'datetime'	=> array(
		'TODAY'		=> '오늘',
		'TOMORROW'	=> '내일',
		'YESTERDAY'	=> '어제',
		'AGO'		=> array(
			0	=> '1분 내',
			1	=> '%d분 전',
			2	=> '%d분 전',
		),

		'Sunday'	=> '일요일',
		'Monday'	=> '월요일',
		'Tuesday'	=> '화요일',
		'Wednesday'	=> '수요일',
		'Thursday'	=> '목요일',
		'Friday'	=> '금요일',
		'Saturday'	=> '토요일',

		'Sun'		=> '일',
		'Mon'		=> '월',
		'Tue'		=> '화',
		'Wed'		=> '수',
		'Thu'		=> '목',
		'Fri'		=> '금',
		'Sat'		=> '토',

		'January'	=> '1월',
		'February'	=> '2월',
		'March'		=> '3월',
		'April'		=> '4월',
		'May'		=> '5월',
		'June'		=> '6월',
		'July'		=> '7월',
		'August'	=> '8월',
		'September'	=> '9월',
		'October'	=> '10월',
		'November'	=> '11월',
		'December'	=> '12월',

		'Jan'		=> '1월',
		'Feb'		=> '2월',
		'Mar'		=> '3월',
		'Apr'		=> '4월',
		'May_short'	=> '5월',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> '6월',
		'Jul'		=> '7월',
		'Aug'		=> '8월',
		'Sep'		=> '9월',
		'Oct'		=> '10월',
		'Nov'		=> '11월',
		'Dec'		=> '12월',

	),

    // Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'			=> 'UTC',
		'UTC_OFFSET'		=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'	=> 'UTC+9',
		'Etc/GMT-8'	=> 'UTC+8',
		'Etc/GMT-7'	=> 'UTC+7',
		'Etc/GMT-6'	=> 'UTC+6',
		'Etc/GMT-5'	=> 'UTC+5',
		'Etc/GMT-4'	=> 'UTC+4',
		'Etc/GMT-3'	=> 'UTC+3',
		'Etc/GMT-2'	=> 'UTC+2',
		'Etc/GMT-1'	=> 'UTC+1',
		'Etc/GMT+1'	=> 'UTC-1',
		'Etc/GMT+2'	=> 'UTC-2',
		'Etc/GMT+3'	=> 'UTC-3',
		'Etc/GMT+4'	=> 'UTC-4',
		'Etc/GMT+5'	=> 'UTC-5',
		'Etc/GMT+6'	=> 'UTC-6',
		'Etc/GMT+7'	=> 'UTC-7',
		'Etc/GMT+8'	=> 'UTC-8',
		'Etc/GMT+9'	=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> '아프리카/아비장',
		'Africa/Accra'		=> '아프리카/아크라',
		'Africa/Addis_Ababa'	=> '아프리카/아디스아바바',
		'Africa/Algiers'	=> '아프리카/알제',
		'Africa/Asmara'		=> '아프리카/아스마라',
		'Africa/Bamako'		=> '아프리카/바마코',
		'Africa/Bangui'		=> '아프리카/방기',
		'Africa/Banjul'		=> '아프리카/반줄',
		'Africa/Bissau'		=> '아프리카/비사우',
		'Africa/Blantyre'	=> '아프리카/블랜타이어',
		'Africa/Brazzaville'	=> '아프리카/브라자빌',
		'Africa/Bujumbura'	=> '아프리카/부줌부라',
		'Africa/Cairo'		=> '아프리카/카이로',
		'Africa/Casablanca'	=> '아프리카/카사블랑카',
		'Africa/Ceuta'		=> '아프리카/세우타',
		'Africa/Conakry'	=> '아프리카/코나크리',
		'Africa/Dakar'		=> '아프리카/다카르',
		'Africa/Dar_es_Salaam'	=> '아프리카/다르에스살람',
		'Africa/Djibouti'	=> '아프리카/지부티',
		'Africa/Douala'		=> '아프리카/두알라',
		'Africa/El_Aaiun'	=> '아프리카/엘아이운',
		'Africa/Freetown'	=> '아프리카/프리타운',
		'Africa/Gaborone'	=> '아프리카/가보로네',
		'Africa/Harare'		=> '아프리카/하라레',
		'Africa/Johannesburg'	=> '아프리카/요하네스버그',
		'Africa/Juba'		=> '아프리카/주바',
		'Africa/Kampala'	=> '아프리카/캄팔라',
		'Africa/Khartoum'	=> '아프리카/하르툼',
		'Africa/Kigali'		=> '아프리카/키갈리',
		'Africa/Kinshasa'	=> '아프리카/킨샤사',
		'Africa/Lagos'		=> '아프리카/라고스',
		'Africa/Libreville'	=> '아프리카/리브르빌',
		'Africa/Lome'		=> '아프리카/로메',
		'Africa/Luanda'		=> '아프리카/루안다',
		'Africa/Lubumbashi'	=> '아프리카/루붐바시',
		'Africa/Lusaka'		=> '아프리카/루사카',
		'Africa/Malabo'		=> '아프리카/말라보',
		'Africa/Maputo'		=> '아프리카/마푸토',
		'Africa/Maseru'		=> '아프리카/마세루',
		'Africa/Mbabane'	=> '아프리카/음바바네',
		'Africa/Mogadishu'	=> '아프리카/모가디슈',
		'Africa/Monrovia'	=> '아프리카/몬로비아',
		'Africa/Nairobi'	=> '아프리카/나이로비',
		'Africa/Ndjamena'	=> '아프리카/은자메나',
		'Africa/Niamey'		=> '아프리카/니아메',
		'Africa/Nouakchott'	=> '아프리카/누악쇼트',
		'Africa/Ouagadougou'	=> '아프리카/와가두구',
		'Africa/Porto-Novo'	=> '아프리카/포르토노보',
		'Africa/Sao_Tome'	=> '아프리카/상투메',
		'Africa/Tripoli'	=> '아프리카/트리폴리',
		'Africa/Tunis'		=> '아프리카/튀니스',
		'Africa/Windhoek'	=> '아프리카/빈트후크',

		'America/Adak'		=> '아메리카/아닥',
		'America/Anchorage'	=> '아메리카/앵커리지',
		'America/Anguilla'	=> '아메리카/앵귈라',
		'America/Antigua'	=> '아메리카/앤티가',
		'America/Araguaina'	=> '아메리카/아라과이나',

		'America/Argentina/Buenos_Aires'	=> '아메리카/아르헨티나/부에노스 아이레스',
		'America/Argentina/Catamarca'	=> '아메리카/아르헨티나/카타마르카',
		'America/Argentina/Cordoba'	=> '아메리카/아르헨티나/코르도바',
		'America/Argentina/Jujuy'	=> '아메리카/아르헨티나/후후이',
		'America/Argentina/La_Rioja'	=> '공정/아르헨티나/라리오하',
		'America/Argentina/Mendoza'	=> '아메리카/아르헨티나/멘도사',
		'America/Argentina/Rio_Gallegos'	=> '아메리카/아르헨티나/리오 가예고스',
		'America/Argentina/Salta'	=> '아메리카/아르헨티나/살타',
		'America/Argentina/San_Juan'	=> '아메리카/아르헨티나/산후안',
		'America/Argentina/San_Luis'	=> '아메리카/아르헨티나/산루이스',
		'America/Argentina/Tucuman'	=> '페어리/아르헨티나/산루이스',
		'America/Argentina/Ushuaia'	=> '아메리카/아르헨티나/우슈아이아',

		'America/Aruba'			=> '아메리카/아루바',
		'America/Asuncion'		=> '아메리카/아순시온',
		'America/Atikokan'		=> '아메리카/아티코칸',
		'America/Bahia'			=> '아메리카/바이아',
		'America/Bahia_Banderas'	=> '아메리카/바이아 반데라스',
		'America/Barbados'		=> '아메리카/바베이도스',
		'America/Belem'			=> '아메리카/벨렘',
		'America/Belize'		=> '아메리카/벨리즈',
		'America/Blanc-Sablon'	=> '아메리카/Blanc-Sablon',
		'America/Boa_Vista'		=> '아메리카/보아 비스타',
		'America/Bogota'		=> '아메리카/보고타',
		'America/Boise'			=> '똑바로/보이시',
		'America/Cambridge_Bay'	=> '아메리카/케임브리지 베이',
		'America/Campo_Grande'	=> '아메리카/캄포 그란데',
		'America/Cancun'		=> '아메리카/Cancun',
		'America/Caracas'		=> '아메리카/카라카스',
		'America/Cayenne'		=> '아메리카/카이엔',
		'America/Cayman'		=> '아메리카/케이맨',
		'America/Chicago'		=> '아메리카/시카고',
		'America/Chihuahua'		=> '똑바로/치와와',
		'America/Costa_Rica'	=> '아메리카/코스타리카',
		'America/Creston'		=> '아메리카/크레스톤',
		'America/Cuiaba'		=> '아메리카/쿠이아바',
		'America/Curacao'		=> '아메리카/퀴라소',
		'America/Danmarkshavn'	=> '아메리카/덴마크샤븐',
		'America/Dawson'		=> '아메리카/도슨',
		'America/Dawson_Creek'	=> '아메리카/도슨 크릭',
		'America/Denver'		=> '아메리카/덴버',
		'America/Detroit'		=> '아메리카/디트로이트',
		'America/Dominica'		=> '아메리카/도미니카',
		'America/Edmonton'		=> '아메리카/에드먼턴',
		'America/Eirunepe'		=> '아메리카/에이루네페',
		'America/El_Salvador'	=> '아메리카/엘살바도르',
		'America/Fortaleza'		=> '아메리카/포르탈레자',
		'America/Glace_Bay'		=> '아메리카/글레이스 베이',
		'America/Godthab'		=> '아메리카/갓탑',
		'America/Goose_Bay'		=> '아메리카/구스베이',
		'America/Grand_Turk'	=> '아메리카/그랜드 터크',
		'America/Grenada'		=> '아메리카/그레나다',
		'America/Guadeloupe'	=> '아메리카/과들루프',
		'America/Guatemala'		=> '아메리카/과테말라',
		'America/Guayaquil'		=> '아메리카/과야킬',
		'America/Guyana'		=> '아메리카/가이아나',
		'America/Halifax'		=> '아메리카/핼리팩스',
		'America/Havana'		=> '아메리카/하바나',
		'America/Hermosillo'		=> '아메리카/에르모시요',
		'America/Indiana/Indianapolis'	=> '아메리카/인디아나/인디애나폴리스',
		'America/Indiana/Knox'		=> '아메리카/인디애나/녹스',
		'America/Indiana/Marengo'	=> '아메리카/인디아나/마렝고',
		'America/Indiana/Petersburg'	=> '아메리카/인디아나/피터스버그',
		'America/Indiana/Tell_City'	=> '아메리카/인디아나/텔시티',
		'America/Indiana/Vevay'		=> '아메리카/인디아나/베베이',
		'America/Indiana/Vincennes'	=> '아메리카/인디아나/뱅센',
		'America/Indiana/Winamac'	=> '아메리카/인디아나/위나맥',
		'America/Inuvik'		=> '아메리카/이누비크',
		'America/Iqaluit'		=> '아메리카/이칼루이트',
		'America/Jamaica'		=> '아메리카/자메이카',
		'America/Juneau'		=> '아메리카/주노',
		'America/Kentucky/Louisville'	=> '아메리카/켄터키/루이빌',
		'America/Kentucky/Monticello'	=> '아메리카/켄터키/몬티첼로',
		'America/Kralendijk'	=> '아메리카/크랄렌데이크',
		'America/La_Paz'		=> '아메리카/라파스',
		'America/Lima'			=> '아메리카/리마',
		'America/Los_Angeles'	=> '아메리카/로스앤젤레스',
		'America/Lower_Princes'	=> '아메리카/Lower Princes',
		'America/Maceio'		=> '아메리카/마세이오',
		'America/Managua'		=> '아메리카/마나과',
		'America/Manaus'		=> '아메리카/마나우스',
		'America/Marigot'		=> '아메리카/마리고',
		'America/Martinique'	=> '아메리카/마르티니크',
		'America/Matamoros'		=> '아메리카/마타모로스',
		'America/Mazatlan'		=> '아메리카/마사틀란',
		'America/Menominee'		=> '아메리카/메노미니',
		'America/Merida'		=> '아메리카/메리다',
		'America/Metlakatla'	=> '아메리카/메틀라카틀라',
		'America/Mexico_City'	=> '아메리카/멕시코시티',
		'America/Miquelon'		=> '아메리카/미클롱',
		'America/Moncton'		=> '아메리카/멍크턴',
		'America/Monterrey'		=> '아메리카/몬테레이',
		'America/Montevideo'	=> '아메리카/몬테비데오',
		'America/Montreal'		=> '아메리카/몬트리올',
		'America/Montserrat'	=> '아메리카/몬세라트',
		'America/Nassau'		=> '아메리카/나소',
		'America/New_York'		=> '아메리카/뉴욕',
		'America/Nipigon'		=> '아메리카/니피곤',
		'America/Nome'			=> '아메리카/놈',
		'America/Noronha'		=> '아메리카/노로냐',
		'America/North_Dakota/Beulah'		=> '아메리카/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> '아메리카/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> '아메리카/North Dakota/New Salem',
		'America/Ojinaga'		=> '아메리카/오지나가',
		'America/Panama'		=> '아메리카/파나마',
		'America/Pangnirtung'	=> '아메리카/Pangnirtung',
		'America/Paramaribo'	=> '아메리카/파라마리보',
		'America/Phoenix'		=> '아메리카/피닉스',
		'America/Port-au-Prince'	=> '아메리카/포르토프랭스',
		'America/Port_of_Spain'	=> '아메리카/포트오브스페인',
		'America/Porto_Velho'	=> '아메리카/포르토 벨류',
		'America/Puerto_Rico'	=> '아메리카/푸에르토리코',
		'America/Rainy_River'	=> '아메리카/레이니 리버',
		'America/Rankin_Inlet'	=> '아메리카/Rankin Inlet',
		'America/Recife'		=> '아메리카/레시피',
		'America/Regina'		=> '아메리카/리자이나',
		'America/Resolute'		=> '아메리카/Resolute',
		'America/Rio_Branco'	=> '아메리카/리오 브랑코',
		'America/Santa_Isabel'	=> '아메리카/산타 이사벨',
		'America/Santarem'		=> '아메리카/산타렘',
		'America/Santiago'		=> '아메리카/산티아고',
		'America/Santo_Domingo'	=> '아메리카/산토도밍고',
		'America/Sao_Paulo'		=> '아메리카/상파울루',
		'America/Scoresbysund'	=> '아메리카/스코어스비선드',
		'America/Shiprock'		=> '아메리카/십록',
		'America/Sitka'			=> '아메리카/시트카',
		'America/St_Barthelemy'	=> '아메리카/세인트. 바르텔레미',
		'America/St_Johns'		=> '아메리카/세인트. 존스',
		'America/St_Kitts'		=> '아메리카/세인트. 키츠',
		'America/St_Lucia'		=> '아메리카/세인트. 루시아',
		'America/St_Thomas'		=> '아메리카/세인트. 도마',
		'America/St_Vincent'	=> '아메리카/세인트. 빈센트',
		'America/Swift_Current'	=> '아메리카/',
		'America/Tegucigalpa'	=> '아메리카/테구시갈파',
		'America/Thule'			=> '아메리카/툴레',
		'America/Thunder_Bay'	=> '아메리카/선더 베이',
		'America/Tijuana'		=> '아메리카/티후아나',
		'America/Toronto'		=> '아메리카/토론토',
		'America/Tortola'		=> '아메리카/토르톨라',
		'America/Vancouver'		=> '아메리카/밴쿠버',
		'America/Whitehorse'	=> '아메리카/화이트호스',
		'America/Winnipeg'		=> '아메리카/위니펙',
		'America/Yakutat'		=> '아메리카/',
		'America/Yellowknife'	=> '아메리카/옐로나이프',

		'Antarctica/Casey'		=> '남극 대륙/케이시',
		'Antarctica/Davis'		=> '남극 대륙/데이비스',
		'Antarctica/DumontDUrville'	=> '남극 대륙/DumontDUurville',
		'Antarctica/Macquarie'	=> '남극 대륙/맥쿼리',
		'Antarctica/Mawson'	=> '남극 대륙/모슨',
		'Antarctica/McMurdo'	=> '남극 대륙/맥머도',
		'Antarctica/Palmer'	=> '남극 대륙/팔머',
		'Antarctica/Rothera'	=> '남극 대륙/로테라',
		'Antarctica/South_Pole'	=> '남극 대륙/사우스 폴',
		'Antarctica/Syowa'	=> '남극 대륙/쇼와',
		'Antarctica/Vostok'	=> '남극 대륙/보스토크',

		'Arctic/Longyearbyen'	=> '북극/롱이어뷔엔',

		'Asia/Aden'		=> '아시아/아덴',
		'Asia/Almaty'		=> '아시아/알마티',
		'Asia/Amman'		=> '아시아/암만',
		'Asia/Anadyr'		=> '아시아/',
		'Asia/Aqtau'		=> '아시아/악타우',
		'Asia/Aqtobe'		=> '아시아/악토베',
		'Asia/Ashgabat'		=> '아시아/',
		'Asia/Baghdad'		=> '아시아/바그다드',
		'Asia/Bahrain'		=> '아시아/바레인',
		'Asia/Baku'		=> '아시아/바쿠',
		'Asia/Bangkok'		=> '아시아/방콕',
		'Asia/Beirut'		=> '아시아/베이루트',
		'Asia/Bishkek'		=> '아시아/비슈케크',
		'Asia/Brunei'		=> '아시아/브루나이',
		'Asia/Choibalsan'	=> '아시아/초이발산',
		'Asia/Chongqing'	=> '아시아/충칭',
		'Asia/Colombo'		=> '아시아/콜롬보',
		'Asia/Damascus'		=> '아시아/다마스쿠스',
		'Asia/Dhaka'		=> '아시아/다카',
		'Asia/Dili'		=> '아시아/딜리',
		'Asia/Dubai'		=> '아시아/두바이',
		'Asia/Dushanbe'		=> '아시아/두샨바',
		'Asia/Gaza'		=> '아시아/가자',
		'Asia/Harbin'		=> '아시아/하얼빈',
		'Asia/Hebron'		=> '아시아/헤브론',
		'Asia/Ho_Chi_Minh'	=> '아시아/호치민',
		'Asia/Hong_Kong'	=> '아시아/홍콩',
		'Asia/Hovd'		=> '아시아/Hovd',
		'Asia/Irkutsk'		=> '아시아/이르쿠츠크',
		'Asia/Jakarta'		=> '아시아/자카르타',
		'Asia/Jayapura'		=> '아시아/자야푸라',
		'Asia/Jerusalem'	=> '아시아/예루살렘',
		'Asia/Kabul'		=> '아시아/카불',
		'Asia/Kamchatka'	=> '아시아/캄티카',
		'Asia/Karachi'		=> '아시아/카라치',
		'Asia/Kashgar'		=> '아시아/카슈가르',
		'Asia/Kathmandu'	=> '아시아/카트만두',
		'Asia/Khandyga'		=> '아시아/칸디가',
		'Asia/Kolkata'		=> '케이스/콜카타',
		'Asia/Krasnoyarsk'	=> '아시아/크라스노야르스크',
		'Asia/Kuala_Lumpur'	=> '아시아/쿠알라룸푸르',
		'Asia/Kuching'		=> '아시아/쿠칭',
		'Asia/Kuwait'		=> '아시아/쿠웨이트',
		'Asia/Macau'		=> '아시아/마카오',
		'Asia/Magadan'		=> '아시아/마가단',
		'Asia/Makassar'		=> '아시아/마카사르',
		'Asia/Manila'		=> '아시아/마닐라',
		'Asia/Muscat'		=> '아시아/무스카트',
		'Asia/Nicosia'		=> '아시아/니코시아',
		'Asia/Novokuznetsk'	=> '아샤/노보쿠즈네츠크',
		'Asia/Novosibirsk'	=> '아시아/노보시비르스크',
		'Asia/Omsk'		=> '아시아/옴스크',
		'Asia/Oral'		=> '아시아/오럴',
		'Asia/Phnom_Penh'	=> '아시아/프놈펜',
		'Asia/Pontianak'	=> '아시아/폰티아낙',
		'Asia/Pyongyang'	=> '아시아/평양',
		'Asia/Qatar'		=> '아시아/카타르',
		'Asia/Qyzylorda'	=> '아시아/키질로르다',
		'Asia/Rangoon'		=> '아시아/랑군',
		'Asia/Riyadh'		=> '아시아/리야드',
		'Asia/Sakhalin'		=> '아시아/사할린',
		'Asia/Samarkand'	=> '아시아/사마르칸트',
		'Asia/Seoul'		=> '아시아/서울',
		'Asia/Shanghai'		=> '아시아/상하이',
		'Asia/Singapore'	=> '아시아/싱가포르',
		'Asia/Taipei'		=> '아시아/타이베이',
		'Asia/Tashkent'		=> '아시아/타슈켄트',
		'Asia/Tbilisi'		=> '아시아/트빌리시',
		'Asia/Tehran'		=> '아시아/트빌리시',
		'Asia/Thimphu'		=> '아시아/팀부',
		'Asia/Tokyo'		=> '아시아/도쿄',
		'Asia/Ulaanbaatar'	=> '아시아/울란바토르',
		'Asia/Urumqi'		=> '아시아/우루무치',
		'Asia/Ust-Nera'		=> '아시아/우스트네라',
		'Asia/Vientiane'	=> '아시아/우스트네라',
		'Asia/Vladivostok'	=> '아시아/블라디보스토크',
		'Asia/Yakutsk'		=> '아시아/야쿠츠크',
		'Asia/Yekaterinburg'	=> '아시아/예카테린부르크',
		'Asia/Yerevan'		=> '아시아/예레반',

		'Atlantic/Azores'	=> '대서양/아조레스',
		'Atlantic/Bermuda'	=> '대서양/버뮤다',
		'Atlantic/Canary'	=> '대서양/카나리아',
		'Atlantic/Cape_Verde'	=> '대서양/카보베르데',
		'Atlantic/Faroe'	=> '대서양/페로',
		'Atlantic/Madeira'	=> '대서양/마데이라',
		'Atlantic/Reykjavik'	=> '대서양/레이캬비크',
		'Atlantic/South_Georgia'	=> '대서양/사우스조지아',
		'Atlantic/St_Helena'	=> '대서양/세인트. 헬레나',
		'Atlantic/Stanley'	=> '대서양/스탠리',

		'Australia/Adelaide'	=> '호주/애들레이드',
		'Australia/Brisbane'	=> '호주/브리즈번',
		'Australia/Broken_Hill'	=> '호주/브로큰힐',
		'Australia/Currie'	=> '호주/커리',
		'Australia/Darwin'	=> '호주/다윈',
		'Australia/Eucla'	=> '호주/유클라',
		'Australia/Hobart'	=> '호주/호바트',
		'Australia/Lindeman'	=> '호주/린데만',
		'Australia/Lord_Howe'	=> '호주/로드 하우',
		'Australia/Melbourne'	=> '호주/멜버른',
		'Australia/Perth'	=> '호주/퍼스',
		'Australia/Sydney'	=> '호주/시드니',

		'Europe/Amsterdam'	=> '유럽/암스테르담',
		'Europe/Andorra'	=> '유럽/안도라',
		'Europe/Athens'		=> '유럽/아테네',
		'Europe/Belgrade'	=> '유럽/베오그라드',
		'Europe/Berlin'		=> '유럽/베를린',
		'Europe/Bratislava'	=> '유럽/브라티슬라바',
		'Europe/Brussels'	=> '유럽/브뤼셀',
		'Europe/Bucharest'	=> '유럽/부쿠레슈티',
		'Europe/Budapest'	=> '유럽/부다페스트',
		'Europe/Busingen'	=> '유럽/뷔징겐',
		'Europe/Chisinau'	=> '유럽/키시나우',
		'Europe/Copenhagen'	=> '유럽/코펜하겐',
		'Europe/Dublin'		=> '유럽/더블린',
		'Europe/Gibraltar'	=> '유럽/지브롤터',
		'Europe/Guernsey'	=> '유럽/건지',
		'Europe/Helsinki'	=> '유럽/헬싱키',
		'Europe/Isle_of_Man'	=> '유럽/Isle of Man',
		'Europe/Istanbul'	=> '유럽/이스탄불',
		'Europe/Jersey'		=> '유럽/저지',
		'Europe/Kaliningrad'	=> '유럽/칼리닌그라드',
		'Europe/Kiev'		=> '유럽/키예프',
		'Europe/Lisbon'		=> '유럽/리스본',
		'Europe/Ljubljana'	=> '유럽/류블랴나',
		'Europe/London'		=> '유럽/런던',
		'Europe/Luxembourg'	=> '유럽/룩셈부르크',
		'Europe/Madrid'		=> '유럽/마드리드',
		'Europe/Malta'		=> '유럽/몰타',
		'Europe/Mariehamn'	=> '유럽/마리에함',
		'Europe/Minsk'		=> '유럽/민스크',
		'Europe/Monaco'		=> '유럽/모나코',
		'Europe/Moscow'		=> '유럽/모스크바',
		'Europe/Oslo'		=> '유럽/오슬로',
		'Europe/Paris'		=> '유럽/파리',
		'Europe/Podgorica'	=> '유럽/포드고리차',
		'Europe/Prague'		=> '유럽/프라하',
		'Europe/Riga'		=> '유럽/리가',
		'Europe/Rome'		=> '유럽/로마',
		'Europe/Samara'		=> '유럽/사마라',
		'Europe/San_Marino'	=> '유럽/산마리노',
		'Europe/Sarajevo'	=> '유럽/사라예보',
		'Europe/Simferopol'	=> '유럽/심페로폴',
		'Europe/Skopje'		=> '유럽/스코페',
		'Europe/Sofia'		=> '유럽/소피아',
		'Europe/Stockholm'	=> '유럽/스톡홀름',
		'Europe/Tallinn'	=> '유럽/탈린',
		'Europe/Tirane'		=> '유럽/티란',
		'Europe/Uzhgorod'	=> '유럽/우주고로드',
		'Europe/Vaduz'		=> '유럽/파두츠',
		'Europe/Vatican'	=> '유럽/바티칸',
		'Europe/Vienna'		=> '유럽/비엔나',
		'Europe/Vilnius'	=> '유럽/빌니우스',
		'Europe/Volgograd'	=> '유럽/볼고그라드',
		'Europe/Warsaw'		=> '유럽/바르샤바',
		'Europe/Zagreb'		=> '유럽/자그레브',
		'Europe/Zaporozhye'	=> '유럽/자포로제',
		'Europe/Zurich'		=> '유럽/취리히',

		'Indian/Antananarivo'	=> '인디언/안타나나리보',
		'Indian/Chagos'		=> '인디언/차고스',
		'Indian/Christmas'	=> '인디언/크리스마스',
		'Indian/Cocos'		=> '인디언/코코스',
		'Indian/Comoro'		=> '인디언/코모로',
		'Indian/Kerguelen'	=> '인디언/케르겔렌',
		'Indian/Mahe'		=> '인디언/Mahe',
		'Indian/Maldives'	=> '인디언/몰디브',
		'Indian/Mauritius'	=> '인디언/모리셔스',
		'Indian/Mayotte'	=> '인디언/Mayotte',
		'Indian/Reunion'	=> '인디언/레위니옹',

		'Pacific/Apia'		=> '태평양/아피아',
		'Pacific/Auckland'	=> '태평양/오클랜드',
		'Pacific/Chatham'	=> '태평양/채텀',
		'Pacific/Chuuk'		=> '태평양/추크',
		'Pacific/Easter'	=> '태평양/부활절',
		'Pacific/Efate'		=> '태평양/에파테',
		'Pacific/Enderbury'	=> '태평양/엔더베리',
		'Pacific/Fakaofo'	=> '태평양/파카오포',
		'Pacific/Fiji'		=> '태평양/피지',
		'Pacific/Funafuti'	=> '태평양/푸나푸티',
		'Pacific/Galapagos'	=> '태평양/갈라파고스',
		'Pacific/Gambier'	=> '태명양/갬비어',
		'Pacific/Guadalcanal'	=> '태평양/과달카날',
		'Pacific/Guam'		=> '태평양/괌',
		'Pacific/Honolulu'	=> '태평양/호놀룰루',
		'Pacific/Johnston'	=> '태평양/존스턴',
		'Pacific/Kiritimati'	=> '태평양/키리티마티',
		'Pacific/Kosrae'	=> '태평양/코스라에',
		'Pacific/Kwajalein'	=> '태평양/콰잘레인',
		'Pacific/Majuro'	=> '태평양/마주로',
		'Pacific/Marquesas'	=> '태평양/마르퀘사스',
		'Pacific/Midway'	=> '태평양/미드웨이',
		'Pacific/Nauru'		=> '태평양/나우루',
		'Pacific/Niue'		=> '태평양/니우에',
		'Pacific/Norfolk'	=> '태평양/노퍽',
		'Pacific/Noumea'	=> '태평양/누메아',
		'Pacific/Pago_Pago'	=> '태평양/파고파고',
		'Pacific/Palau'		=> '태평양/팔라우',
		'Pacific/Pitcairn'	=> '태평양/핏케언',
		'Pacific/Pohnpei'	=> '태평양/폰페이',
		'Pacific/Port_Moresby'	=> '태평양/포트모르즈비',
		'Pacific/Rarotonga'	=> '태평양/라로통가',
		'Pacific/Saipan'	=> '태평양/사이판',
		'Pacific/Tahiti'	=> '태평양/타히티',
		'Pacific/Tarawa'	=> '태평양/타라와',
		'Pacific/Tongatapu'	=> '태평양/통가타푸',
		'Pacific/Wake'		=> '태평양/웨이크',
		'Pacific/Wallis'	=> '태평양/월리스',
	),

     // The value is only an example and will get replaced by the current time on view
     	'dateformats'	=> array(
		'Y-m-d H:i' 			=> '2024-01-23 12:34',
		'd M Y, H:i'			=> '01 Jan 2007, 13:37',
		'd M Y H:i'			=> '01 Jan 2007 13:37',
		'M jS, \'y, H:i'		=> 'Jan 1st, \'07, 13:37',
		'D M d, Y g:i a'		=> 'Mon Jan 01, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> 'January 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'Today, 13:37 / 01 Jan 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'Today, 1:37 pm / January 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
'default_dateformat'	=> 'Y-M-d H:i', // 2024-01-01 18:23

));
